### ISSUE TITLE
TypeError: We is not a function

### ISSUE THREAD

**Issue by a2nt** [wejs/we#123]
Hi I was going to deploy new we,js project and followed guide step by step, but it doesn't work
```javascript
we loadLocales
/usr/local/lib/node_modules/we/lib/helpers.js:15
        throw e;
        ^

TypeError: We is not a function
    at Object.getWe (/usr/local/lib/node_modules/we/lib/helpers.js:9:14)
    at Command.run (/usr/local/lib/node_modules/we/bin/loadLocales.js:20:16)
    at Command.listener (/usr/local/lib/node_modules/we/node_modules/commander/index.js:287:8)
    at emitTwo (events.js:100:13)
    at Command.emit (events.js:185:7)
    at Command.parseArgs (/usr/local/lib/node_modules/we/node_modules/commander/index.js:541:12)
    at Command.parse (/usr/local/lib/node_modules/we/node_modules/commander/index.js:427:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/we/bin/we:118:9)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3
```

**Comment by albertosouza** [comment]
Hi @a2nt ,

Now `we-cli` returns one prototype, see all changes in your CHANGELOG.md: https://github.com/wejs/we-core/blob/master/CHANGELOG.md#changes
 
Update your we cli and generator-wejs: `npm install -g we generator-wejs`

## For update old projects: 

You need to update your local modules `npm outdated`

And update you we cli, app.js and gulpfile.js to work with we.js v1.0.x:
```
var We = require('we-core'); // the prototype
var we = new We(); // the app
```

## For update new projects:

If you have one new project run `yo wejs:[projectType]` again in a folder above your project.

**Comment by albertosouza** [comment]
The problem here are in old generator but after the update they are working.

Thanks for this feedback and feel free to reopen if find any problem related to this issue
